package com.github.wdstar.springboot.example;

import lombok.extern.slf4j.Slf4j;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.info.BuildProperties;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
public class Hello {

	@Autowired
	@Nullable
	private BuildProperties buildProperties;

	@RequestMapping("/greet")
	public String greet() {
		// This log object is generated by the `@Slf4j` annotation.
		logger.info("Hello.greet() called.");

		return "Hello World!";
	}

	@RequestMapping("/version")
	public String version() {
		logger.info("Hello.version() called.");
		String version = "Not Found.";
		if (buildProperties != null) {
			version = buildProperties.getVersion();
		}

		return version;
	}

}
